@Api_HostAddress = http://localhost:5031

GET {{Api_HostAddress}}/
Accept: application/json

### signup
#@signup
POST {{Api_HostAddress}}/users/signup
Content-Type: application/json
Accept: application/json

{
    "username": "test-{{$timestamp}}",
    "password": "test"
}

### webfinger
#@webfinger
GET {{Api_HostAddress}}/.well-known/webfinger?resource=acct:test-{{$timestamp}}@localhost